name: test
on: [push, pull_request]

jobs:
  test-nix:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - name: Install Mage
        run: go run mage.go EnsureMage
      - name: Run Tests in Bash
        run: mage test
        shell: bash
        env:
          TEST_SHELL: bash
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - name: Install Mage
        run: go run mage.go EnsureMage
      - name: Run Mage in CMD
        run: mage test
        shell: cmd
        env:
          TEST_SHELL: cmd
      - name: Run Mage in PowerShell
        run: mage test
        shell: powershell
        env:
          TEST_SHELL: powershell
      - name: Run Mage in Git Bash
        run: mage test
        shell: bash
        env:
          TEST_SHELL: mingw64
